version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-export:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo hi
      - deploy: 
          command: echo $CIRCLE_BRANCH
workflows:
    build-and-export:
      jobs:
        - build-and-export