version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-export:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install gh-pages
            - run: npm run build
            - run: npm run export
      - deploy: 
          command: if [ $CIRCLE_BRANCH = master ]; then node node_modules/gh-pages/bin/gh-pages.js --dist out; fi
workflows:
    build-and-export:
      jobs:
        - build-and-export