version: 2.1
jobs:
  build-and-export:
    docker: 
      - image: circleci/node@1.1.6
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
          - run: npm run build
          - run: npm run export
workflows:
    build-and-export:
      jobs:
        - build-and-export