version: 2.1
jobs:
  build-and-export:
    docker: 
      - image: circleci/node@1.1.6
    steps:
      - checkout
      - run: 
        name: Install
        command: npm install
      - run: npm run build
        name: Build
      - run:
        name: Export
        command: npm run export
workflows:
    build-and-export:
      jobs:
        - build-and-export