version: 2.1
orbs:
  node: circleci/node@1.1.6
  node2: circleci/node@1.1.6
jobs:
  build-and-export:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm run export
  docs-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node2/with-cache:
        steps:
          - run: echo testy testy
workflows:
    build-and-export:
      jobs:
        - build-and-export
        - docs-deploy:
          requires:
            - build-and-export