version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-export:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
          - run: npm install -g --silent gh-pages@2.0.1
          - run: npm run build
          - run: npm run export
          - run: git config user.email "andrew.griffiths@holidayextras.com"
          - run: git config user.name "andrewghx"
workflows:
    build-and-export:
      jobs:
        - build-and-export