version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-export:
    environment:
      NODE_ENV: production
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install gh-pages
            - run: npm run build
            - run: npm run export
      - deploy: 
          command: if [ $CIRCLE_BRANCH = master ]; then git config user.email "ci-build@griffithsa.co.uk"; git config user.name "ci-build" ; fi
      - deploy:
          command: if [ $CIRCLE_BRANCH = master ]; then node node_modules/gh-pages/bin/gh-pages.js --dist out; fi
      - add_ssh_keys:
          fingerprints:
            - b5:24:a9:5c:f6:72:d1:91:aa:73:20:44:fa:21:71:e4
workflows:
    build-and-export:
      jobs:
        - build-and-export:
            filters:
              branches:
                ignore:
                  - gh-pages